CREATE TABLE rsa_encrypts (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL
		REFERENCES users(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	p BIGINT NOT NULL,
	q BIGINT NOT NULL,
	e BIGINT NOT NULL,
	d BIGINT NOT NULL,
	m BIGINT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	completed_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE rsa_decrypts (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL
		REFERENCES users(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	p BIGINT NOT NULL,
	q BIGINT NOT NULL,
	e BIGINT NOT NULL,
	d BIGINT NOT NULL,
	c BIGINT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	completed_at TIMESTAMP WITH TIME ZONE
);
