CREATE TABLE dss_signs (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL
		REFERENCES users(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	n_p BIGINT NOT NULL,
	n_q BIGINT NOT NULL,
	g BIGINT NOT NULL,
	h TEXT NOT NULL,
	m BIGINT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	completed_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE dss_verifies (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL
		REFERENCES users(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	n_p BIGINT NOT NULL,
	n_q BIGINT NOT NULL,
	g BIGINT NOT NULL,
	h TEXT NOT NULL,
	pk BIGINT NOT NULL,
	m BIGINT NOT NULL,
	r BIGINT NOT NULL,
	s BIGINT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	completed_at TIMESTAMP WITH TIME ZONE
);
